default_language_version:
  python: python3.9
exclude: reports
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix, lf]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
    - id: reorder-python-imports
      args: [--py37-plus, "--application-directories=alq_racing"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      args: [--config=.flake8]
      additional_dependencies:
        - flake8-builtins==1.5.3
        - flake8-comprehensions==3.3.0
        - flake8-bugbear==20.1.4
        - flake8-eradicate==1.0.0
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: [-s, B101]
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.790
#    hooks:
#      - id: mypy
