scour \
  -i ../design/maiwar.svg \
  -o output.svg \
  --enable-comment-stripping \
  --enable-id-stripping \
  --enable-viewboxing \
  --remove-metadata \
  --remove-titles \
  --shorten-ids \
  --indent=none \
  --strip-xml-prolog \
  --verbose \
  --protect-ids-list=location-colmslie,location-indooroopilly,location-west-end,location-oxley-creek,location-colleges-crossing,location-wynnum,location-lota-creek,location-nudgee,location-cabbage-tree-creek,location-sandgate,location-shorncliffe,current-date
